### ISSUE TITLE
Version 2.21.0 released according to GitHub but not available in Central?

### ISSUE THREAD

**Issue by gaeljw** [open-telemetry/opentelemetry-java-instrumentation#15056]
### Describe the bug

Even though version 2.21.0 has been released 2 days ago according to the GitHub release status, some artifacts are not yet available in Central.

For instance, the javaagent is not available: https://central.sonatype.com/artifact/io.opentelemetry.javaagent/opentelemetry-javaagent/versions

I know this can take some time for an artifact to be available but this seems abnormal. Just wanted to raise it so that you can check if there was an issue in the release process or if it's something on Central side that is delaying.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

B/A

### Javaagent or library instrumentation version

B/A

### Environment

N/A

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

**Comment by TiddoLangerak** [comment]
Similarly, the [BOM](https://mvnrepository.com/artifact/io.opentelemetry.instrumentation/opentelemetry-instrumentation-bom/2.21.0) published to maven central is broken as a result of this. It points to certain unpublished packages:

<img width="916" height="167" alt="Image" src="https://github.com/user-attachments/assets/3270354f-3c58-46d4-b3ad-db5e2d103af0" />

**Comment by laurit** [comment]
Should be fixed now.

**Comment by TiddoLangerak** [comment]
@laurit - I still can't see the packages on maven central. E.g. the [javaagent](https://mvnrepository.com/artifact/io.opentelemetry.javaagent/opentelemetry-javaagent) still lists 2.20.1 as its latest version.

<img width="1659" height="528" alt="Image" src="https://github.com/user-attachments/assets/394bc88d-1158-43d8-8b17-d5d23ec90bbb" />

**Comment by gaeljw** [comment]
@TiddoLangerak mvnrepository.com has itself some extra delay, and even miss some packages sometimes, better to use https://central.sonatype.com/artifact/io.opentelemetry.javaagent/opentelemetry-javaagent/versions which is the "official" reference.
