### ISSUE TITLE
Consider tweaking the build to only run tests for affected files.

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#541]
I use this technique of reading the git diff to run tests in monorepos

https://github.com/curioswitch/curiostack/blob/master/tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/ci/CurioGenericCiPlugin.java

This agent is even more of a monorepo than than many I've experienced :) I generally like them but think this sort of "only build affected targets" technique is what makes or breaks the experience.

**Comment by iNikem** [comment]
I will repeat myself from #526 :)

"I would really love to try #490 first. It may, in theory, reduce build times significantly for us."

**Comment by trask** [comment]
@anuraaga is this resolved by all of the gradle build cache work?

**Comment by anuraaga** [comment]
@iNikem Did we ever make the build cache public for users' builds? If not, I think this could still be a reasonable alternative.

**Comment by iNikem** [comment]
We still have an unresolved issue that remote build cache does not work for developers machine.

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
